apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: 1000-card-game-client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arkadiuszkrakowiak.com
      http:
        paths:
          - path: /projects/1000(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: game-client
              servicePort: 80
