apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1000-card-game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - arkadiuszkrakowiak.com
        - www.arkadiuszkrakowiak.com
      secretName: arkadiuszkrakowiak-com-tls
  rules:
    - host: arkadiuszkrakowiak.com
      http:
        paths:
          - path: /projects/1000/api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-game-server
                port:
                  number: 8080
